### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by joepie91** [llambda/connect-session-knex#13]
RIght now, the module README doesn't mention that the session table is created on runtime. Perhaps it'd be a good idea to add this? It took me a bit of time to figure this out myself, and when I recommended the module to somebody else just now, they asked me the exact same question, so there's clearly demand for this kind of information.

Additionally, the documentation is a bit sparse in general - possibly there are more things missing from it?

**Comment by llambda** [comment]
Fair point :smile: I added more words to the readme.
