### ISSUE TITLE
dbCleanup broken with sqlite3

### ISSUE THREAD

**Issue by samizzo** [llambda/connect-session-knex#14]
The SQL generated by the `dbCleanup` function doesn't work with sqlite3. The where clause generated is:

`expired < CAST('2015-11-06T02:52:00.375Z' as timestamp)`

The cast returns the number 2015, because sqlite3 doesn't have a `timestamp` type, and when it applies its column affinity logic to that type name, it results in a numeric type (see https://www.sqlite.org/datatype3.html#affname).

A correct where clause should probably use the `datetime` function like this:

`datetime(expired) < datetime('2015-11-06T02:52:00.375Z')`

sqlite3 doesn't actually have *any* datetime data type unfortunately. I think the `get` function would be similarly broken, but by chance it works because the comparison is:

`CAST('2015-11-06T03:31:25.059Z' as timestamp) <= expired`

which is pretty much always true unless the year changes.

I'm testing a local fix so I'll issue a pull request soon.

**Comment by llambda** [comment]
Nice catch! Looking forward to your PR.

**Comment by samizzo** [comment]
Damnit, I just set up a brand new project to test with, and it's not happening any more! I'm using node 5.0.0 and sqlite3 64-bit, but when I found the bug I was using 32-bit and an older node version. I'll need to do some more testing.

**Comment by samizzo** [comment]
Ok, actually I was able to repro it. Embarrassingly, I had left in debug code to automatically clear the entire store! So it was still happening even with latest node etc. I've issued the PR, #15.

**Comment by llambda** [comment]
Thank you very much. Nice work!
