### ISSUE TITLE
Should use setTimeout instead of setInterval

### ISSUE THREAD

**Issue by joepie91** [llambda/connect-session-knex#22]
Currently, this library is [using setInterval](https://github.com/llambda/connect-session-knex/blob/master/index.js#L123) for cleanup scheduling. However, this will not deal well with slow cleanup queries - it should be using a recursive setTimeout instead, as described [here](https://zetafleet.com/blog/2010/04/why-i-consider-setinterval-to-be-harmful.html).

**Comment by llambda** [comment]
This is a good idea! Great suggestion.
