### ISSUE TITLE
Tests not exiting because of uncanceled timeout

### ISSUE THREAD

**Issue by Tiim** [llambda/connect-session-knex#55]
I am trying to write unit tests for my rest api and after they are run the proccess doesn't exit.
After some poking around i'm confident that this is the case because this library uses a timeout that  doesn't get removed.

I found the function [stopDbCleanup](https://github.com/llambda/connect-session-knex/blob/master/index.js#L421-L426) in the source code and but it seems like it doesn't exist in the version released to npm.

I'm trying to use it like this:

```js
...
  const store = new KnexSessionStore({
    knex,
    tablename: 'session',
    createtable: true,
    clearInterval: 1000 * 60 * 30, //30 Min
  });

  fastify.addHook('onClose', (instance, done) => {
    store.stopDbCleanup(); // TypeError: store.stopDbCleanup is not a function
    done();
  });

  fastify.register(session, {
    cookie: {
      httpOnly: true,
      secure: config.isProduction,
      maxAge: 1000 * 60 * 60 * 24 * 30, //30d
    },
    saveUninitialized: false,
    secret: config.sessionSecret,
    store,
  });
...
```

Is there a workaround I could put in the `onClose` hook to stop the timeout?

Thanks

**Comment by llambda** [comment]
`1.5.0` has been published with this method added.
